lib/nadia/api.ex
Timeout bug https://github.com/zhyu/nadia/issues/2 is fixed.
=> fix timeout bug

.travis.yml, lib/nadia.ex, lib/nadia/parser.ex, mix.exs, test/nadia/parser_test.exs
https://github.com/zhyu/nadia/issues/5 multi-alias
=> Support for elixir 1.2 features

README.md, config/config.exs.example, lib/nadia/api.ex
default timeout from http poison is 8s.
=> improve timeout algo

lib/nadia/api.ex
My naive implementation of 'with' feature from elixir 1.2, please tell me if it awful, and i'll go away to learn more elixir ;)
=> use with from elixir 1.2

lib/nadia/model.ex
https://github.com/zhyu/nadia/issues/3 enough to add support of supergroups or i miss something??
=> add optional fields to the Message object to support supergroup

lib/nadia/model.ex
https://github.com/zhyu/nadia/issues/10 support for inlinefeedback
=> add ChosenInlineResult type and chosen_inline_result field to the Update

lib/nadia.ex, test/nadia_test.exs
https://github.com/zhyu/nadia/issues/11 here to start. you can tell me what need to improve or transform
=> very naive implementation get_file_link function

lib/nadia.ex
https://telegram.org/blog/channels-2-0#silent-messages
=> Add an optional disable_notification parameter 

lib/nadia/model.ex
Recent changes in Bot API from May 6, 2016
https://core.telegram.org/bots/api#recent-changes
=> Added fields emoji and forward_from_chat

fixture/vcr_cassettes/get_chat.json, fixture/vcr_cassettes/get_chat_administrators.json, fixture/vcr_cassettes/get_chat_member.json, fixture/vcr_cassettes/get_chat_members_count.json, fixture/vcr_cassettes/leave_chat.json, lib/nadia.ex, lib/nadia/model.ex, lib/nadia/parser.ex, test/nadia_test.exs
closes https://github.com/zhyu/nadia/issues/31
Since all new methods only for group managing still don't know how to properly test this
EDIT: I mean, how to add tests. so I'm testing it with my bot)
EDIT2: give me some time, i guess i can do tests)
=> Add support for Bot API 2.1

README.md
Also, I've bumped the dependency version in the document.
@zhyu , thanks for this project!
=> Add some example usage code to README

config/config.exs.example, lib/nadia/api.ex
Allows nadia to make requests to the telegram api via a proxy
=> Adds proxy support

lib/nadia/parser.ex
I tested, works fine! From the issue #54
=> add CallbackQuery to the parser

lib/nadia/api.ex
> warning: Enum.filter_map/3 is deprecated, use Enum.filter/2 + Enum.map/2 or for comprehensions
=> remove deprecation warnings

lib/nadia.ex, lib/nadia/api.ex, lib/nadia/behaviour.ex
I add the user api behaviour for mocking with Plataformatec's [mox](https://github.com/plataformatec/mox)
from Jose Valim
> One of the guidelines in Elixir is that every time you you generate a function in the user code it should be to abide to some behaviour, so yes, you need behaviours.
=> add behaviour for mocking

README.md, config/config.exs.example, lib/nadia/api.ex, lib/nadia/config.ex, lib/nadia/graph/api.ex, test/nadia/config_test.exs
Fixes #41 
Ask and you shall receive (give or take 10 months).
=> Allow base url to be configurable for both the normal and graph api

.formatter.exs, lib/nadia.ex, lib/nadia/api.ex, lib/nadia/behaviour.ex, lib/nadia/config.ex, lib/nadia/graph.ex, lib/nadia/graph/api.ex, lib/nadia/graph/model.ex, lib/nadia/graph/parser.ex, lib/nadia/model.ex, lib/nadia/model/inline_query_result.ex, lib/nadia/model/input_message_content.ex, lib/nadia/parser.ex, mix.exs, test/nadia/api_test.exs, test/nadia/config_test.exs, test/nadia/graph_test.exs, test/nadia/parser_test.exs, test/nadia_test.exs
With elixir 1.6 we have the new oficial formatter 😄 ( https://medium.com/blackode/code-formatter-the-big-feature-in-elixir-v1-6-0-f6572061a4ba )
I was doing the changes to fix #53 but I was also changing the format of the files, because my editor auto format the source code on save.
I'll open this PR with the actual source code formatted, feel free to accept or reject it if you don't like the formatter.
Cheers, and welcome back!
=> Format the code with new elixir formatter!

lib/nadia/api.ex, lib/nadia/parser.ex
=> Nicer error reporting for invalid tokens

fixture/vcr_cassettes/get_webhook_info.json, lib/nadia.ex, lib/nadia/model.ex, lib/nadia/parser.ex, test/nadia/parser_test.exs, test/nadia_test.exs
=> Added delete webhook info into docs

fixture/vcr_cassettes/delete_message.json, lib/nadia.ex, test/nadia_test.exs
Docs: https://core.telegram.org/bots/api#deletemessage
=> Added deleteMessage support

lib/nadia/model.ex, lib/nadia/model/input_message_content.ex
Just exactly as the title says :)
=> Derive Jason encoder for embedded models

fixture/vcr_cassettes/pin_chat_message.json, fixture/vcr_cassettes/unpin_chat_message.json, lib/nadia.ex, test/nadia_test.exs
Hi @zhyu ! 
As part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) I decided to submit this PR to implement `pinChatMessage` and `unpinChatMessage` as per issue #94 
Hope that helps! 
Cheers
=> Implement pinChatMessage and unpinChatMessage, with tests

fixture/vcr_cassettes/send_animation.json, lib/nadia.ex, lib/nadia/behaviour.ex, test/nadia_test.exs
Implemented [send_animation](https://core.telegram.org/bots/api#sendanimation)
=> Implement send_animation

lib/nadia/parser.ex, test/nadia/parser_test.exs
=> adds `:edited_message` to `@keys_of_message` in `Nadia.Parser`
